browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: latest
  - name: microsoftedge
    version: latest
  - name: iphone
    version: 11.2
    platform: Mac 10.12
  - name: ipad
    version: latest
  - name: android
    version: '6.0'
