browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: '11'
  - name: microsoftedge
    version: latest
  - name: iphone
    version: latest
  - name: ipad
    version: latest
  - name: android
    version: '6.0'
