sudo: false
language: node_js

matrix:
  fast_finish: true
  include:
  - node_js: 4
    env: CMD=test
  - node_js: 6
    env: CMD=test
  - node_js: 8
    env: CMD=test
  - node_js: stable
    env: CMD=report-coverage
  - node_js: stable
    env: CMD=test-browsers
    addons:
      sauce_connect:
        username: level-ci
      jwt:
        secure: FH6lh3KKopAv+WbL3OsKWhYABW5pyOR2hHXYg8rhB2Bup8EGMWsVTTMxcFOTn1tMt5b0dylgQjb59W28Ir3Jz3ncuc1XiDy+O12RYNlXsb2WtgQttEJJ0beSK8ItXr8LTyAs8+dWLO6hS8bf3dw97AzynWkeJLY9vZcDSB4ncn4=
      hosts:
        - airtap.local

script:
  - DEBUG=airtap:* npm run $CMD

notifications:
  email: false
